# Generated by Django 5.2.6 on 2025-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED-HI', 'Medium-High'), ('MED', 'Medium'), ('LOW', 'Low')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED-HI', 'Medium-High'), ('MED', 'Medium'), ('LOW', 'Low')], default='MED', max_length=10),
        ),
    ]
