# Generated by Django 5.2.6 on 2025-10-14 06:16

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='report.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED-HI', 'Medium-High'), ('MED', 'Medium-High'), ('LOW', 'Low')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED-HI', 'Medium-High'), ('MED', 'Medium-High'), ('LOW', 'Low')], default='MED', max_length=10),
        ),
    ]
