# Generated by Django 5.2.6 on 2025-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_asset_level_asset_lft_asset_rght_asset_tree_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED-HI', 'Medium-High'), ('MED', 'Medium'), ('LOW', 'Low')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MED-HI', 'Medium-High'), ('MED', 'Medium'), ('LOW', 'Low')], default='MED', max_length=10),
        ),
    ]
