# Generated by Django 5.2.6 on 2025-10-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_asset_priority_alter_report_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
