# Generated by Django 5.2.6 on 2025-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
