# Generated by Django 5.2.6 on 2025-10-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_remove_asset_position_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='report.asset'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
