# Generated by Django 5.2.6 on 2025-10-14 11:58

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_asset_parent_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='report.asset'),
        ),
    ]
